# Generated by Django 5.2.4 on 2025-07-31 06:01

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
