"""
Django settings for projauth project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url


load_dotenv()  # Load .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nb9q&r2p4v!+%opo&g^^nznu&eqaio6#x!m$dsszzoax-e!z#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'  # Convert string to boolean
print(f"DEBUG value: {DEBUG}")
'''
New Comment example
'''
ALLOWED_HOSTS = ['*']

# Add here your deployment HOSTS
# In production without CSRF_TRUSTED_ORIGINS settings it'll give error
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://localhost:5085',
                        'http://127.0.0.1:8000', 'http://127.0.0.1:5085', 'https://djnago-blog-auth.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'users',
    'ckeditor',
    'django_bleach'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'projauth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projauth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv('DB_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DB_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Location for collected static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# For Production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------- Bleach CKEditor settings ----------
# ---------- tags ----------
BLEACH_ALLOWED_TAGS = [
    # text
    'p', 'br', 'hr', 'pre', 'code', 'blockquote', 'q',
    'strong', 'b', 'em', 'i', 'u', 'strike', 's', 'del', 'ins',
    'sub', 'sup', 'mark', 'small',
    # headings
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    # lists
    'ul', 'ol', 'li', 'dl', 'dt', 'dd',
    # tables
    'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td', 'caption',
    # media / embed
    'img', 'figure', 'figcaption', 'iframe', 'object', 'embed', 'param',
    'video', 'audio', 'source', 'track',
    # generic wrappers
    'div', 'span', 'section', 'article', 'aside', 'header', 'footer',
    # links
    'a',
]

# ---------- attributes ----------
BLEACH_ALLOWED_ATTRIBUTES = {
    '*': ['class', 'id', 'title', 'style', 'data-*'],
    'a': ['href', 'title', 'target', 'rel'],
    'img': ['src', 'alt', 'width', 'height', 'style'],
    'iframe': ['src', 'width', 'height', 'frameborder', 'allowfullscreen', 'style'],
    'table': ['width', 'height', 'border', 'cellspacing', 'cellpadding', 'style'],
    'th': ['scope', 'colspan', 'rowspan', 'width', 'height', 'style'],
    'td': ['colspan', 'rowspan', 'width', 'height', 'style'],
}

# ---------- styles (the exhaustive list) ----------
BLEACH_ALLOWED_STYLES = [
    # font
    'font-family', 'font-size', 'font-style', 'font-weight', 'font-variant',
    # text
    'color', 'background-color', 'text-decoration', 'text-decoration-color',
    'text-decoration-line', 'text-decoration-style', 'text-align',
    'text-indent', 'text-transform', 'letter-spacing', 'line-height',
    'word-spacing', 'white-space', 'vertical-align',
    # box
    'display', 'float', 'clear',
    'width', 'height', 'max-width', 'max-height', 'min-width', 'min-height',
    'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
    'padding', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
    'border', 'border-top', 'border-right', 'border-bottom', 'border-left',
    'border-width', 'border-style', 'border-color',
    'border-radius',
    # positioning / transform
    'position', 'top', 'right', 'bottom', 'left', 'z-index',
    'transform', 'transform-origin',
    # flex / grid (rare but sometimes used)
    'flex', 'flex-direction', 'justify-content', 'align-items',
    'grid-template-columns', 'grid-template-rows',
    # table
    'border-collapse', 'border-spacing',
    # misc
    'opacity', 'overflow', 'box-sizing', 'cursor',
]


BLEACH_STRIP_TAGS = True
